#  ARQUIVO PARA FAZER O DEPLOY LOCAL DO BANCO DE DADOS
#  USAR O COMANDO: docker-compose up -d

version: "3.1"

services:      
  db:
    image: mysql:8.0
    container_name: banco_produtos_vendas_clientes
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./src/database/:/db
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    networks:
      - backend

  api:
    depends_on:
      - db
    build: .
    command: yarn start
    env_file: ./.env
    container_name: api_produtos_vendas_clientes
    restart: unless-stopped
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    networks:
      - backend
 
volumes:
  db:
 
networks:
  backend:
